// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityDialog;

  EntityDialog = {};

  */;


  ig.module('game.entities.dialog').requires('game.entities.common.base-entity').defines(function() {
    return EntityDialog = EntityBaseEntity.extend({
      size: {
        x: 1,
        y: 1
      },
      collides: ig.Entity.COLLIDES.NEVER,
      animSheet: new ig.AnimationSheet('media/dialogs/dialog-lines.png', 1, 1),
      lines: new ig.Image('media/dialogs/dialog-lines.png'),
      corners: new ig.Image('media/dialogs/dialog-corners.png'),
      visible: false,
      font: new ig.Font('media/fonts/arial-12-normal-black.png'),
      text: [],
      currentPos: 0,
      padding: 5,
      cornerSize: {
        width: 4,
        height: 4
      },
      ctx: null,
      init: function(x, y, settings) {
        this.addAnim('idle', 1, [0]);
        this.ctx = ig.system.context;
        return this.parent(x, y, settings);
      },
      draw: function() {
        var height, paddedHeight, paddedWidth, startX, startY, width;
        if (!this.visible) {
          return;
        }
        startX = this.pos.x;
        startY = this.pos.y;
        width = this.font.widthForString(this.text[this.currentPos]);
        paddedWidth = width + (this.padding * 2);
        height = this.font.heightForString(this.text[this.currentPos]);
        paddedHeight = height + (this.padding * 2);
        this.corners.drawTile(startX, startY, 0, this.cornerSize.width);
        this.corners.drawTile(startX + this.cornerSize.width + paddedWidth, startY, 0, this.cornerSize.width, this.cornerSize.height, true);
        this.corners.drawTile(startX, startY + this.cornerSize.height + paddedHeight, 0, this.cornerSize.width, this.cornerSize.height, false, true);
        this.corners.drawTile(startX + this.cornerSize.width + paddedWidth, startY + this.cornerSize.height + paddedHeight, 0, this.cornerSize.width, this.cornerSize.height, true, true);
        this.lines.drawTile(startX + this.cornerSize.width, startY, 0, paddedWidth, 1);
        this.lines.drawTile(startX + this.cornerSize.width, startY + paddedHeight + (this.cornerSize.height * 2), 0, paddedWidth, 1);
        this.lines.drawTile(startX, startY + this.cornerSize.height, 0, 1, paddedHeight);
        this.lines.drawTile(startX + paddedWidth + (this.cornerSize.width * 2), startY + this.cornerSize.height, 0, 1, paddedHeight);
        this.drawRect(startX + this.cornerSize.width, startY + this.cornerSize.height, paddedWidth, paddedHeight);
        this.drawRect(startX + this.cornerSize.width - 1, startY + 1, paddedWidth + 2, this.cornerSize.height);
        this.drawRect(startX + this.cornerSize.width - 1, startY + paddedHeight + this.cornerSize.height, paddedWidth + 1, this.cornerSize.height);
        this.drawRect(startX + 1, startY + this.cornerSize.height, this.cornerSize.width, paddedHeight);
        this.drawRect(startX + paddedWidth + this.cornerSize.width - 1, startY + this.cornerSize.height, this.cornerSize.width + 1, paddedHeight);
        return this.font.draw(this.text[this.currentPos], startX + this.cornerSize.width + this.padding, startY + this.cornerSize.height + this.padding);
      },
      drawRect: function(x, y, width, height, fillColor) {
        if (fillColor == null) {
          fillColor = 'white';
        }
        this.ctx.fillStyle = fillColor;
        return this.ctx.fillRect(x, y, width, height);
      }
    });
  });

}).call(this);
