// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityEnemy;

  EntityEnemy = {};

  */;


  ig.module('game.entities.enemy').requires('impact.entity').defines(function() {
    return EntityEnemy = ig.Entity.extend({
      size: {
        x: 48,
        y: 64
      },
      collides: ig.Entity.COLLIDES.PASSIVE,
      type: ig.Entity.TYPE.B,
      checkAgainst: ig.Entity.TYPE.A,
      animSheet: new ig.AnimationSheet('media/characters/hero.png', 48, 64),
      idleAnimSpeed: 1,
      init: function(x, y, settings) {
        this.addAnim('idleDown', this.idleAnimSpeed, [0]);
        return this.parent(x, y, settings);
      },
      update: function() {
        return this.parent();
      }
    });
  });

}).call(this);
