// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityInventory;

  EntityInventory = {};

  */;


  ig.module('game.entities.inventory').requires('game.entities.common.static-entity').defines(function() {
    return EntityInventory = EntityBaseEntity.extend({
      size: {
        x: 320,
        y: 200
      },
      collides: ig.Entity.COLLIDES.NEVER,
      items: {},
      addItem: function(item) {
        var _base, _ref;
        if ((_ref = (_base = this.items)[item]) == null) {
          _base[item] = 0;
        }
        return this.items[item] += 1;
      }
    });
  });

}).call(this);
