// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityLog;

  EntityLog = {};

  */;


  ig.module('game.entities.log').requires('game.entities.common.static-entity', 'game.common.flasher').defines(function() {
    return EntityLog = EntityStaticEntity.extend({
      size: {
        x: 25,
        y: 25
      },
      type: ig.Entity.TYPE.A,
      checkAgainst: ig.Entity.TYPE.A,
      collides: ig.Entity.COLLIDES.NEVER,
      animSheet: new ig.AnimationSheet('media/environment/log.png', 36, 25),
      pickup: new ig.Sound('media/sounds/pickup.*'),
      lifeTimer: null,
      lifeTime: 10,
      flasher: null,
      flashStartTime: 9,
      init: function(x, y, settings) {
        this.addAnim('idle', 0.2, [0, 1, 2, 3, 2, 1, 0]);
        this.lifeTimer = new ig.Timer();
        this.flasher = new Flasher(this);
        return this.parent(x, y, settings);
      },
      update: function() {
        if (this.lifeTimer.delta() > this.flashStartTime) {
          this.flasher.startFlash();
        }
        if (this.lifeTimer.delta() > this.lifeTime) {
          this.kill();
        }
        return this.parent();
      },
      draw: function() {
        this.flasher.draw();
        return this.parent();
      },
      check: function(other) {
        if (other.name === 'player') {
          this.pickup.play();
          other.inventory.addItem('log');
          return this.kill();
        }
      }
    });
  });

}).call(this);
