// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityLog;

  EntityLog = {};

  */;


  ig.module('game.entities.log').requires('game.entities.common.static-entity').defines(function() {
    return EntityLog = EntityStaticEntity.extend({
      size: {
        x: 54,
        y: 19
      },
      type: ig.Entity.TYPE.A,
      checkAgainst: ig.Entity.TYPE.A,
      collides: ig.Entity.COLLIDES.NEVER,
      animSheet: new ig.AnimationSheet('media/environment/log.png', 54, 19),
      pickup: new ig.Sound('media/sounds/pickup.*'),
      lifeTimer: null,
      lifeTime: 10,
      init: function(x, y, settings) {
        this.lifeTimer = new ig.Timer();
        return this.parent(x, y, settings);
      },
      update: function() {
        if (this.lifeTimer.delta() > this.lifeTime) {
          this.kill();
        }
        return this.parent();
      },
      check: function(other) {
        if (other.name === 'player') {
          this.pickup.play();
          other.inventory.addItem('log');
          return this.kill();
        }
      }
    });
  });

}).call(this);
