// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityPlayer;

  EntityPlayer = {};

  */;


  ig.module('game.entities.player').requires('game.entities.common.base-entity', 'game.entities.inventory', 'game.entities.weapons.axe', 'game.entities.weapons.fireball').defines(function() {
    return EntityPlayer = EntityBaseEntity.extend({
      size: {
        x: 16,
        y: 20
      },
      offset: {
        x: 17,
        y: 22
      },
      collides: ig.Entity.COLLIDES.ACTIVE,
      type: ig.Entity.TYPE.A,
      animSheet: new ig.AnimationSheet('media/characters/player_v1.png', 50, 50),
      name: 'player',
      states: {
        DEFAULT: 1,
        IN_INVENTORY: 2
      },
      state: null,
      facing: 'Down',
      velocity: 300,
      maxVel: {
        x: 500,
        y: 500
      },
      idleAnimSpeed: 1,
      movingAnimSpeed: 0.1,
      movementAllowed: true,
      inventory: null,
      weaponAnimTimer: null,
      weaponAnimTime: 0.1,
      activeWeapon: 'axe',
      weapons: ['axe', 'fireball'],
      health: 50,
      mana: 50,
      maxMana: 50,
      manaRegenerateDelay: 3,
      manaRegenerateDelayTimer: null,
      manaRegenerateRate: 1,
      manaRegenerateTimer: null,
      fireballManaCost: 5,
      init: function(x, y, settings) {
        this.addAnim('idleDown', this.idleAnimSpeed, [0]);
        this.addAnim('idleUp', this.idleAnimSpeed, [7]);
        this.addAnim('idleRight', this.idleAnimSpeed, [14]);
        this.addAnim('idleLeft', this.idleAnimSpeed, [21]);
        this.addAnim('walkDown', this.movingAnimSpeed, [0, 1, 0, 2]);
        this.addAnim('walkUp', this.movingAnimSpeed, [7, 8, 7, 9]);
        this.addAnim('walkRight', this.movingAnimSpeed, [14, 15, 14, 16]);
        this.addAnim('walkLeft', this.movingAnimSpeed, [21, 22, 21, 23]);
        this.addAnim('axeDown', this.movingAnimSpeed, [3]);
        this.addAnim('axeUp', this.movingAnimSpeed, [4]);
        this.addAnim('axeRight', this.movingAnimSpeed, [5]);
        this.addAnim('axeLeft', this.movingAnimSpeed, [6]);
        this.addAnim('fireballDown', this.movingAnimSpeed, [10]);
        this.addAnim('fireballUp', this.movingAnimSpeed, [11]);
        this.addAnim('fireballRight', this.movingAnimSpeed, [12]);
        this.addAnim('fireballLeft', this.movingAnimSpeed, [13]);
        this.state = this.states.DEFAULT;
        this.manaRegenerateTimer = new ig.Timer();
        if (!ig.global.wm) {
          this.inventory = ig.game.spawnEntity(EntityInventory);
          this.inventory.pos.x = (ig.system.width - this.inventory.size.x) / 2;
          this.inventory.pos.y = (ig.system.height - this.inventory.size.y) / 2;
        }
        this.parent(x, y, settings);
        return ig.game.player = this;
      },
      update: function() {
        var _ref;
        if (((_ref = this.manaRegenerateDelayTimer) != null ? _ref.delta() : void 0) > this.manaRegenerateDelay) {
          if (this.manaRegenerateTimer.delta() > 1) {
            if (this.mana + this.manaRegenerateRate <= this.maxMana) {
              this.mana += this.manaRegenerateRate;
            }
            this.manaRegenerateTimer.reset();
          }
        }
        this.handleButtons();
        return this.parent();
      },
      draw: function() {
        if (!ig.global.wm) {
          this.zIndex = parseInt(this.pos.y + this.size.y);
          ig.game.sortEntitiesDeferred();
          this.inventory.isVisible = this.state === this.states.IN_INVENTORY;
        }
        return this.parent();
      },
      handleButtons: function() {
        var futureMana, weapon;
        if (!this.movementAllowed) {
          this.reset();
          return;
        }
        if (ig.input.pressed('switchWeapon')) {
          this.switchWeapon();
        }
        /* Inventory/Menu Navigation
        */

        if (ig.input.pressed('inventory')) {
          this.reset();
          if (this.state === this.states.IN_INVENTORY) {
            this.movementAllowed = true;
            this.state = this.states.DEFAULT;
          } else {
            this.movementAllowed = false;
            this.state = this.states.IN_INVENTORY;
          }
        }
        /* Weapons
        */

        if (ig.input.pressed('attack')) {
          this.currentAnim = this.anims[this.activeWeapon + this.facing];
          this.weaponAnimTimer = new ig.Timer();
          futureMana = this.mana - this.fireballManaCost;
          if ((this.activeWeapon === 'fireball' && futureMana >= 0) || this.activeWeapon === 'axe') {
            if (this.activeWeapon === 'fireball') {
              this.mana -= this.fireballManaCost;
              this.manaRegenerateDelayTimer = new ig.Timer();
            }
            weapon = ig.game.spawnEntity('Entity' + this.activeWeapon.substring(0, 1).toUpperCase() + this.activeWeapon.substring(1), 0, 0, {
              facing: this.facing
            });
            weapon.pos = this.getWeaponCoordinates(weapon);
          }
        }
        /* Movement
        */

        if (ig.input.state('up')) {
          this.currentAnim = this.anims.walkUp;
          this.facing = 'Up';
          this.vel.x = 0;
          this.vel.y = -this.velocity;
          if (ig.input.state('right')) {
            return this.vel.x = this.velocity;
          } else if (ig.input.state('left')) {
            return this.vel.x = -this.velocity;
          }
        } else if (ig.input.state('down')) {
          this.currentAnim = this.anims.walkDown;
          this.facing = 'Down';
          this.vel.x = 0;
          this.vel.y = this.velocity;
          if (ig.input.state('right')) {
            return this.vel.x = this.velocity;
          } else if (ig.input.state('left')) {
            return this.vel.x = -this.velocity;
          }
        } else if (ig.input.state('left')) {
          this.currentAnim = this.anims.walkLeft;
          this.facing = 'Left';
          this.vel.x = -this.velocity;
          return this.vel.y = 0;
        } else if (ig.input.state('right')) {
          this.currentAnim = this.anims.walkRight;
          this.facing = 'Right';
          this.vel.x = this.velocity;
          return this.vel.y = 0;
        } else {
          if (!ig.input.pressed('attack')) {
            return this.reset();
          }
        }
      },
      getWeaponCoordinates: function(weaponEntity) {
        var pos;
        pos = {
          x: 0,
          y: 0
        };
        switch (this.facing) {
          case 'Up':
            pos.x = this.pos.x;
            pos.y = this.pos.y - weaponEntity.size.y;
            break;
          case 'Down':
            pos.x = this.pos.x;
            pos.y = this.pos.y + this.size.y;
            break;
          case 'Left':
            pos.x = this.pos.x - weaponEntity.size.x;
            pos.y = this.pos.y;
            break;
          case 'Right':
            pos.x = this.pos.x + this.size.x;
            pos.y = this.pos.y;
        }
        return pos;
      },
      switchWeapon: function() {
        var weapon;
        weapon = this.weapons.indexOf(this.activeWeapon) + 1;
        if (weapon > this.weapons.length - 1) {
          weapon = 0;
        }
        return this.activeWeapon = this.weapons[weapon];
      },
      reset: function() {
        if (!(this.weaponAnimTimer != null)) {
          this.currentAnim = this.anims['idle' + this.facing];
        } else {
          if (this.weaponAnimTimer.delta() > this.weaponAnimTime) {
            this.weaponAnimTimer = null;
          }
        }
        this.vel.x = 0;
        return this.vel.y = 0;
      }
    });
  });

}).call(this);
