// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityTree;

  EntityTree = {};

  */;


  ig.module('game.entities.tree').requires('game.entities.common.base-entity').defines(function() {
    return EntityTree = EntityBaseEntity.extend({
      size: {
        x: 85,
        y: 55
      },
      offset: {
        x: 65,
        y: 155
      },
      collides: ig.Entity.COLLIDES.FIXED,
      type: ig.Entity.TYPE.A,
      animSheet: new ig.AnimationSheet('media/environment/tree.png', 220, 211),
      treeStrike: new ig.Sound('media/sounds/tree-strike.*'),
      treeFall: new ig.Sound('media/sounds/tree-fall.*'),
      entityType: 'tree',
      init: function(x, y, settings) {
        this.addAnim('idle', 1000, [0]);
        return this.parent(x, y, settings);
      },
      receiveDamage: function(amount, from) {
        if (this.health - amount > 0) {
          this.treeStrike.play();
        }
        return this.parent(amount, from);
      },
      kill: function() {
        this.treeFall.play();
        return this.parent();
      }
    });
  });

}).call(this);
