// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var Flasher;

  Flasher = {};

  */;


  ig.module('game.common.flasher').requires('game.entities.common.static-entity').defines(function() {
    return Flasher = ig.Class.extend({
      flashTimer: null,
      flashCurrent: 0,
      flashTime: 0.1,
      flashAlphas: [0.5, 1, 0.5, 1],
      flashReceiver: null,
      init: function(flashReceiver) {
        return this.flashReceiver = flashReceiver;
      },
      startFlash: function() {
        return this.flashTimer = new ig.Timer(this.flashTime);
      },
      draw: function() {
        var _ref, _ref1, _ref2;
        if (((_ref = this.flashTimer) != null ? _ref.delta() : void 0) < 0) {
          return this.flashReceiver.currentAnim.alpha = this.flashTimer.delta().map(0, -this.flashTimer.target, this.flashAlphas[this.flashCurrent], ((_ref1 = this.flashCurrent) === 0 || _ref1 === 2 ? 1 : 0.5));
        } else {
          if (this.flashCurrent === 3) {
            this.flashCurrent = 0;
            return this.flashTimer = null;
          } else {
            this.flashCurrent++;
            return (_ref2 = this.flashTimer) != null ? _ref2.reset() : void 0;
          }
        }
      }
    });
  });

}).call(this);
