// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var WeaponManager;

  WeaponManager = {};

  */;


  ig.module('game.common.weapon-manager').requires().defines(function() {
    return WeaponManager = ig.Class.extend({
      weaponAnimTimer: null,
      weaponAnimTime: 0.1,
      init: function(settings) {
        var name, value, _results;
        _results = [];
        for (name in settings) {
          value = settings[name];
          _results.push(this[name] = value);
        }
        return _results;
      },
      update: function() {
        if (ig.input.pressed('switchWeapon')) {
          return this.switchWeapon();
        }
      },
      switchWeapon: function() {
        var weapon;
        weapon = this.weapons.indexOf(this.activeWeapon) + 1;
        if (weapon > this.weapons.length - 1) {
          weapon = 0;
        }
        return this.activeWeapon = this.weapons[weapon];
      },
      weaponIsActive: function() {
        return !(this.weaponAnimTimer != null);
      },
      reset: function() {
        var _ref;
        if (((_ref = this.weaponAnimTimer) != null ? _ref.delta() : void 0) > this.weaponAnimTime) {
          return this.weaponAnimTimer = null;
        }
      }
    });
  });

}).call(this);
