// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityBaseEntity;

  EntityBaseEntity = {};

  */;


  ig.module('game.entities.common.base-entity').requires('impact.entity').defines(function() {
    return EntityBaseEntity = ig.Entity.extend({
      init: function(x, y, settings) {
        var sizeY;
        if (!ig.global.wm) {
          sizeY = (this.size != null) && (this.size.y != null) ? this.size.y : 0;
          this.zIndex = parseInt(y + sizeY);
          ig.game.sortEntitiesDeferred();
        }
        return this.parent(x, y, settings);
      }
    });
  });

}).call(this);
