// Generated by CoffeeScript 1.4.0
(function() {
  /*;

  var EntityStaticEntity;

  EntityStaticEntity = {};

  */;


  ig.module('game.entities.common.static-entity').requires('game.entities.common.base-entity').defines(function() {
    return EntityStaticEntity = EntityBaseEntity.extend({
      size: {
        x: 8,
        y: 8
      },
      collides: ig.Entity.COLLIDES.FIXED,
      frame: 0,
      init: function(x, y, settings) {
        this.addAnim('idle', 1, [this.frame]);
        return this.parent(x, y, settings);
      }
    });
  });

}).call(this);
