// Generated by CoffeeScript 1.4.0
(function() {
  var WoodTraderGame, elems;

  WoodTraderGame = {};

  elems = {
    window: $(window),
    canvas: $('#canvas'),
    guiContainer: $('#gui'),
    gui: {
      paused: $('#paused')
    }
  };

  ig.module('game.main').requires('impact.game', 'impact.font', 'impact.debug.debug', 'plugins.impact-splash-loader', 'plugins.director.director', 'game.levels.market1', 'game.levels.forest1', 'game.entities.common.base-entity', 'game.entities.inventory', 'game.entities.inventory-item', 'game.entities.player', 'game.entities.trader', 'game.entities.stall', 'game.entities.tree', 'game.entities.log', 'game.entities.menu', 'game.entities.enemy').defines(function() {
    var MainGame, StartScreen;
    MainGame = ig.Game.extend({
      font: new ig.Font('media/fonts/04b03.font.png'),
      bgMusicMarket: new ig.Sound('media/music/01-A-Night-Of-Dizzy-Spells.*'),
      bgMusicForest: new ig.Sound('media/music/02-Underclocked-Underunderclocked-Mix.*'),
      pauseFx: new ig.Sound('media/sounds/pause.*'),
      unpauseFx: new ig.Sound('media/sounds/unpause.*'),
      player: null,
      director: null,
      sortBy: ig.Game.SORT.POS_Y,
      init: function() {
        $(window).blur(function() {
          return ig.game.pause();
        });
        $(window).focus(function() {
          return ig.game.unpause();
        });
        $(document).keyup(function(e) {
          var _ref;
          if ((_ref = e.which) === 27 || _ref === 80) {
            return ig.game.togglePause();
          }
        });
        ig.input.bind(ig.KEY.LEFT_ARROW, 'left');
        ig.input.bind(ig.KEY.RIGHT_ARROW, 'right');
        ig.input.bind(ig.KEY.UP_ARROW, 'up');
        ig.input.bind(ig.KEY.DOWN_ARROW, 'down');
        ig.input.bind(ig.KEY.SPACE, 'attack');
        ig.input.bind(ig.KEY.ENTER, 'confirm');
        ig.input.bind(ig.KEY.I, 'inventory');
        ig.input.bind(ig.KEY.MOUSE1, 'confirm');
        this.director = new ig.Director(this, [LevelMarket1, LevelForest1]);
        ig.music.loop = true;
        ig.music.volume = 0.5;
        ig.music.add(this.bgMusicMarket, 'market');
        ig.music.add(this.bgMusicForest, 'forest');
        ig.music.play('market');
        return this.director.jumpTo(LevelMarket1);
      },
      update: function() {
        var mainBgMap, mapHeight, mapWidth, x, y;
        this.parent();
        if (this.player != null) {
          x = this.player.pos.x - ig.system.width / 2;
          y = this.player.pos.y - ig.system.height / 2;
          mainBgMap = ig.game.getMapByName('grass');
          mapWidth = mainBgMap.width * mainBgMap.tilesize - ig.system.width;
          mapHeight = mainBgMap.height * mainBgMap.tilesize - ig.system.height;
          x = x < 0 ? 0 : x > mapWidth ? mapWidth : x;
          y = y < 0 ? 0 : y > mapHeight ? mapHeight : y;
          this.screen.x = x;
          return this.screen.y = y;
        }
      },
      draw: function() {
        return this.parent();
      },
      pause: function() {
        var _ref;
        if (!ig.system || !((_ref = ig.system) != null ? _ref.running : void 0)) {
          return;
        }
        this.pauseFx.play();
        ig.music.pause();
        ig.system.stopRunLoop();
        elems.canvas.addClass('inactive');
        return elems.gui.paused.css({
          top: (elems.canvas.height() - elems.gui.paused.height()) / 2,
          left: (elems.canvas.width() - elems.gui.paused.width()) / 2
        }).show();
      },
      unpause: function() {
        var _ref;
        if (!ig.system || ((_ref = ig.system) != null ? _ref.running : void 0)) {
          return;
        }
        this.unpauseFx.play();
        ig.music.play();
        ig.system.startRunLoop();
        elems.canvas.removeClass('inactive');
        return elems.gui.paused.hide();
      },
      togglePause: function() {
        var _ref;
        if ((_ref = ig.system) != null ? _ref.running : void 0) {
          return ig.game.pause();
        } else {
          return ig.game.unpause();
        }
      }
    });
    StartScreen = ig.Game.extend({
      instructText: new ig.Font('media/fonts/04b03.font.png'),
      init: function() {
        return ig.input.bind(ig.KEY.SPACE, 'start');
      },
      update: function() {
        this.parent();
        if (ig.input.pressed('start')) {
          return ig.system.setGame(MainGame);
        }
      },
      draw: function() {
        var x, y;
        this.parent();
        x = ig.system.width / 2;
        y = ig.system.height - 10;
        return this.instructText.draw('Press Space To Start', x, y, ig.Font.ALIGN.CENTER);
      }
    });
    return ig.main('#canvas', StartScreen, 60, elems.canvas.width(), elems.canvas.height(), 1, ig.ImpactSplashLoader);
  });

}).call(this);
