// Generated by CoffeeScript 1.4.0
(function() {
  var WoodTraderGame, elems;

  WoodTraderGame = {};

  elems = {
    window: $(window),
    canvas: $('#canvas'),
    guiContainer: $('#gui'),
    gui: {
      paused: $('#paused')
    }
  };

  ig.module('game.main').requires('impact.game', 'impact.font', 'impact.debug.debug', 'plugins.impact-splash-loader', 'plugins.gui', 'plugins.director.director', 'game.levels.market1', 'game.entities.common.base-entity', 'game.entities.inventory', 'game.entities.inventory-item', 'game.entities.player', 'game.entities.trader', 'game.entities.stall', 'game.entities.menu', 'game.entities.enemy').defines(function() {
    $(window).blur(function() {
      return ig.game.pause();
    });
    $(window).focus(function() {
      return ig.game.unpause();
    });
    WoodTraderGame = ig.Game.extend({
      font: new ig.Font('media/fonts/04b03.font.png'),
      bgtune: new ig.Sound('media/music/01-A-Night-Of-Dizzy-Spells.*'),
      pauseFx: new ig.Sound('media/sounds/pause.*'),
      unpauseFx: new ig.Sound('media/sounds/unpause.*'),
      player: null,
      director: null,
      init: function() {
        ig.input.bind(ig.KEY.LEFT_ARROW, 'left');
        ig.input.bind(ig.KEY.RIGHT_ARROW, 'right');
        ig.input.bind(ig.KEY.UP_ARROW, 'up');
        ig.input.bind(ig.KEY.DOWN_ARROW, 'down');
        ig.input.bind(ig.KEY.SPACE, 'attack');
        ig.input.bind(ig.KEY.ENTER, 'confirm');
        ig.input.bind(ig.KEY.I, 'inventory');
        ig.input.bind(ig.KEY.P, 'pause');
        ig.input.bind(ig.KEY.ESC, 'pause');
        ig.input.bind(ig.KEY.MOUSE1, 'confirm');
        ig.gui.show = false;
        this.director = new ig.Director(this, LevelMarket1);
        ig.music.add(this.bgtune);
        ig.music.volume = 0.5;
        ig.music.play();
        this.director.loadLevel(0);
        return this.addGui();
      },
      update: function() {
        var mainBgMap, mapHeight, mapWidth, x, y;
        this.parent();
        if (this.player) {
          x = this.player.pos.x - ig.system.width / 2;
          y = this.player.pos.y - ig.system.height / 2;
          mainBgMap = ig.game.getMapByName('grass');
          mapWidth = mainBgMap.width * mainBgMap.tilesize - ig.system.width;
          mapHeight = mainBgMap.height * mainBgMap.tilesize - ig.system.height;
          x = x < 0 ? 0 : x > mapWidth ? mapWidth : x;
          y = y < 0 ? 0 : y > mapHeight ? mapHeight : y;
          this.screen.x = x;
          return this.screen.y = y;
        }
      },
      draw: function() {
        this.parent();
        if (ig.gui.show) {
          return ig.gui.draw();
        }
      },
      addGui: function() {
        return ig.gui.element.add({
          name: 'inventory',
          group: 'inventory',
          size: {
            x: 47,
            y: 47
          },
          pos: {
            x: 0,
            y: ig.system.height - 47
          },
          state: {
            normal: {
              image: new ig.Image('media/joystick.png'),
              tile: 2,
              tileSize: 47
            }
          },
          click: function() {
            return console.log('clicked');
          }
        });
      },
      pause: function() {
        var _ref;
        if (!ig.system || !((_ref = ig.system) != null ? _ref.running : void 0)) {
          return;
        }
        this.pauseFx.play();
        ig.music.pause();
        ig.system.stopRunLoop();
        elems.canvas.addClass('inactive');
        return elems.gui.paused.css({
          top: (elems.canvas.height() - elems.gui.paused.height()) / 2,
          left: (elems.canvas.width() - elems.gui.paused.width()) / 2
        }).show();
      },
      unpause: function() {
        var _ref;
        if (!ig.system || ((_ref = ig.system) != null ? _ref.running : void 0)) {
          return;
        }
        this.unpauseFx.play();
        ig.music.play();
        ig.system.startRunLoop();
        elems.canvas.removeClass('inactive');
        return elems.gui.paused.hide();
      }
    });
    return ig.main('#canvas', WoodTraderGame, 60, 960, 720, 1, ig.ImpactSplashLoader);
  });

}).call(this);
